export const BASE_URL = process.env.NEXT_PUBLIC_BACKEND_ENDPOINT

export const requests = {
  auth: BASE_URL + '/api/user/auth',
  user: BASE_URL + '/api/user/getUser',
  getCollection: BASE_URL + '/api/collection/getCollections',
  getAllCollections: BASE_URL + '/api/collection/getAllCollections',
  updateCollection: BASE_URL + '/api/collection/updateCollection',
  trendingNFTs: BASE_URL + '/api/collection/getTrendingCollections',
  getCollectionById: BASE_URL + '/api/collection/get',
  likeCollection: BASE_URL + '/api/collection',
  getSingleNFTDetail: BASE_URL + '/api/image/get',
  getPublicProfile: BASE_URL + '/api/user',
  getFile: BASE_URL + '/api/media',
  updateUser: BASE_URL + '/api/user/updateUser',
  documentPreSigned: BASE_URL + '/api/media/preSignedUrl',
  documentPostSigned: BASE_URL + '/api/media/postSignedUrl',
  getNFTsByCollection: BASE_URL + '/api/collection/getCollectionImages',
  deleteDraftCollection: BASE_URL + '/api/collection/draft',
  getDraftCollection: BASE_URL + '/api/collection/draft',
  getTokenPrice: BASE_URL + '/api/token/getTokenPrice',
  generateImageByStream: BASE_URL + '/api/image/generateImageFromText',
  mintNFTs: BASE_URL + '/api/image/mintNFt',
  getProgress: BASE_URL + '/api/collection/getProgress',
  uploadSingleMetadata: BASE_URL + '/api/image/uploadSingleMetadata',
  banCollection: BASE_URL + '/api/collection/banned',
  banUser: BASE_URL + '/api/user/banned',
  getFeatureDetails: BASE_URL + '/api/getMainPageStats',
  getCreditsTransactionHistory:
    BASE_URL + '/api/credit/getCreditsTransactionHistory',
  getCreditsofUser: BASE_URL + '/api/credit/getCredits',
  createStripeSession: BASE_URL + '/api/stripe/createSession',
  getCreditsSpendHistory:
    BASE_URL + '/api/credit/getCreditsSpendTransactionHistory',
  removeSession: BASE_URL + '/api/stripe/session/',
  checkStripeSubscriptions: BASE_URL + '/api/stripe/activeSubscription/',
  cancelSubscription: BASE_URL + '/api/stripe/subscription/unsubscribe/',
  getCgptTokenOfUser: BASE_URL + '/api/user/cgptTokens/',
  deductCredits: BASE_URL + '/api/credit/deductCredits',
  addCredits: BASE_URL + '/api/credit/addCredits',
  addCreditPurchaseHistory: BASE_URL + '/api/credit/addCreditPurchaseHistory',
  addPayment: BASE_URL + '/api/cryptoPayment/addPayment',
  updatePaymentStatus: BASE_URL + '/api/cryptoPayment/updatePaymentStatus',
}
