export const ComicArray = [
  {
    id: "1",
    name: "Student Boss",
    genre: "Action",
    author: "John Doe",
    description: "This is a test",
    imageUrl: "img/examples/1.jpg",
    likes: 150,
    views: 2000,
    timestamp: 1234567890,
    isEnded: false,
  },
  {
    id: "2",
    name: "Fury Battle",
    genre: "Fantasy",
    author: "John Doe",
    description: "This is a test",
    imageUrl: "img/examples/2.jpg",
    likes: 100,
    views: 1000,
    timestamp: 1234567890,
    isEnded: false,
  },
  {
    id: "3",
    name: "Who am I?",
    genre: "Romance",
    author: "John Doe",
    description: "This is a test",
    imageUrl: "img/examples/3.jpg",
    likes: 300,
    views: 12000,
    timestamp: 1567890,
    isEnded: false,
  },
  {
    id: "4",
    name: "Gru's Adventure",
    genre: "Adventure",
    author: "John Doe",
    description: "This is a test",
    imageUrl: "img/examples/4.jpg",
    likes: 1,
    views: 100,
    timestamp: 1234567890,
    isEnded: true,
  },
  {
    id: "5",
    name: "The Last of Us",
    genre: "Adventure",
    author: "John Doe",
    description: "This is a test",
    imageUrl: "img/examples/5.jpg",
    likes: 10000,
    views: 100000,
    timestamp: 1234567890,
    isEnded: false,
  },
  {
    id: "6",
    name: "Light Ninja",
    genre: "Action",
    author: "John Doe",
    description: "This is a test",
    imageUrl: "img/examples/6.jpg",
    likes: 10000,
    views: 100000,
    timestamp: 1234567890,
    isEnded: true,
  },
];